const PREFIX = 'GITHUB';

export const GET_ALL_REPOSITORIES = `${PREFIX}/GET_ALL_REPOSITORIES`;
export const GET_ALL_REPOSITORIES_SUCCESS = `${PREFIX}/GET_ALL_REPOSITORIES_SUCCESS`;
export const GET_ALL_REPOSITORIES_FAIL = `${PREFIX}/GET_ALL_REPOSITORIES_FAIL`;

export const GET_USER = `${PREFIX}/GET_USER`;
export const GET_USER_SUCCESS = `${PREFIX}/GET_USER_SUCCESS`;
export const GET_USER_FAIL = `${PREFIX}/GET_USER_FAIL`;
